[package]
name = "tentech-api"
version = "0.1.0"
authors = ["Anharu <haruan2394@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
