version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
    - db
  db:
    image: postgres:10.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
